name: CI - Build and Test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET 9
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore ./src/HexaCleanHybArch.Template.Api/HexaCleanHybArch.Template.Api.csproj

      - name: Build solution
        run: dotnet build ./src/HexaCleanHybArch.Template.Api/HexaCleanHybArch.Template.Api.csproj --configuration Release --no-restore

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET 9
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Run Unit Tests
        run: dotnet test ./tests/Unit/HexaCleanHybArch.Template.Tests.Unit.csproj --configuration Release --no-build --logger trx

      - name: Run Integration Tests
        run: dotnet test ./tests/Integration/HexaCleanHybArch.Template.Tests.Integration.csproj --configuration Release --no-build --logger trx
